### ISSUE TITLE
ModuleNotFoundError: No module named 'choldate._choldate'

### ISSUE THREAD

**Issue by wasifmasood** [jcrudy/choldate#9]
Hi, getting the following error after installation, please guide

```
Python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from choldate import cholupdate, choldowndate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rayuser/choldate/choldate/__init__.py", line 3, in <module>
    from ._choldate import cholupdate, choldowndate
ModuleNotFoundError: No module named 'choldate._choldate'
```

**Comment by damienchallet** [comment]
It is solved by pull request #8
